---
subject: Instroomanalyse B {opleiding} HHs
title: "Instroomanalyse B {opleiding} HHs"
subtitle: "Voltijd eerstejaars studenten -- cohorten 2012 tot en met 2021"

## Format en output
output-file: lta-instroomanalyse-b-{opleiding_lcase}_1.0.0.pdf

# Versie
versie: 1.0.0
---

# Inleiding

NB Dit is een template: vervang {opleiding}, {track},
{opleiding_lcase}, {faculteit.} De inleiding bevindt zich in het
document \_quarto.yml. Variabelen komen in \_variables.yml

## Het vraagstuk: dalende instroom

Op verzoek van de opleidingsmanager van de B {opleiding} ({track})
van De HHs heeft het lectoraat Learning Technology & Analytics een
analyse uitgevoerd op de instroom. Sinds 2012 is de instroom van de
opleiding namelijk sterk afgenomen (met xx%) en de faculteit en de
opleiding willen het tij keren.

## Verantwoording

Dit onderzoek is uitgevoerd door Theo Bakker, lector Learning Technology
& Analytics, en {naam}, {functie}. Voor dit onderzoek is de
analyseset van het project Studiedata gebruikt van het team IR &
Analytics van OKC. Daarnaast is de landelijke data van de Vereniging
Hogescholen onderzocht voor een vergelijking met andere opleidingen in
Nederland.

## Selecties

-   Eerstejaars studenten, voltijd, B {opleiding}, track {track},
    cohorten 2012 tot en met 2022[^1].
-   Eerstejaars studenten, voltijd, overige opleidingen faculteit
    {faculteit}, cohorten 2012 tot en met 2022.
-   Eerstejaars studenten, voltijd, Vereniging Hogescholen, cohorten
    2017 tot en met 2022.
-   De instroomcijfers van cohort 2023 zijn nog niet bekend.

[^1]: De dataset van HHs Analytics loopt tot en met het cohort 2022,
    aangezien deze set is gebaseerd op de 1CHO bestanden die vanaf het
    voorjaar ter beschikking komen. Het
    [1CHO](https://duo.nl/zakelijk/hoger-onderwijs/studentenadministratie/bron-controleren/deelnames-en-resultaten-duo-registers.jsp)
    staat voor 1 cijfer HO van de Dienst Uitvoering Onderwijs; het zijn
    alle deelnames en resultaten van studenten in het hoger onderwijs,
    vanaf 1991 tot en met 1 oktober van het afgelopen jaar.

::: {.callout-warning title="Nota Bene"}
Dit rapport beschrijft mogelijke verbanden en correlaties. Oorzakelijke
verbanden (causaliteit) zijn niet aangetoond.
:::

\
**Rapport**: {{< meta title >}}, {{< meta subtitle >}}, versie
{{< meta versie >}}

Den Haag, {{< meta date >}}

 

PS Neem voor vragen contact op via 06-25637172 of per mail
[t.c.bakker\@hhs.nl](mailto:t.c.bakker@hhs.nl).

\newpage

# Aanbevelingen voor conversie, voorlichting, scholenbezoek en interne concurrentie.

*Dit hoofdstuk zal worden ingevuld met aanbevelingen in de tweede versie
van dit rapport.*

\newpage

# Opvallende uitkomsten uit de analyses op instroom, oriëntatie en context

## Opvallende uitkomsten uit de analyses op instroom, oriëntatie en context

1.  **Patronen in instroom** - Het aantal studenten is van 2012 tot en
    met 2021 met 38% gedaald, maar niet alle jaren was er sprake van een
    daling. De sterkste dalingen was er in 2021 (-48% t.o.v. 2012). De
    reden waarom dit in 2021 zo is, is nog onbekend. Mogelijk dat dit
    een corona effect is geweest. Dit is onderwerp voor gesprek.

    In 2017, 2018 en 2022 waren er oplevingen met 32% ten opzichte van
    het voorafgaande jaar. De mogelijke oorzaken hiervan zijn niet
    bekend en onderwerp voor gesprek. Zie hoofdstuk [Algemeen beeld
    instroom] voor de bijbehorende grafieken.

2.  **Regionale spreiding**/**toelevering** - Kenmerkend is dat
    studenten voor deze opleiding overwegend uit de regio komen: te
    bereiken met het openbaar vervoer in de spits in 45 minuten. Tussen
    2012 en 2022 is het toeleveringssgebied van de opleiding versmald.
    In 2012 omvatte dit gehele regio, met een grotere groep studenten
    uit de nabije omgeving van JWP, maar in 2022 was dit met name ten
    oosten van Den Haag minder. Zie hoofdstuk [Regionale spreiding].

3.  **Landelijke trends** - Zie hoofdstuk [Landelijke ontwikkelingen].

    1.  Voor CMD van De HHs geldt dat er in de regio een redelijke
        concurrentie is: binnen de R6 instellingen bieden ook de HR, de
        HvA en HU deze opleiding aan[^2].
        {{< var teksten.instroom_landelijk_R6 >}} Opvallend is dat bij
        geen van deze onderwijsinstellingen er een Corona
        boeggolf-effect te zien is. - *bron: VH*

    2.  De opleiding valt binnen het domein Bètatechniek. Het aantal
        studenten in alle opleidingen samen in dit domein is tussen 2017
        en 2022 met 12% gedaald (van 21.103 naar 18.491). Het aantal
        studenten in dit domein bij De HHs is in deze periode eveneens
        gedaald (-11%; van 1.633 naar 1.452). - *bron: VH*

    3.  Uit de R6-marktaandelen Studielink van week 48 blijkt dat het
        voorlopige marktaandeel van CMD in 2024 is afgenomen ten gunste
        van de HvA. Nota bene: zo vroeg in de aanmelding zijn deze
        gegevens nog niet erg betrouwbaar. - *bron: OKC*

4.  **Trend binnen de faculteit** - Binnen de faculteit ITD is de
    opleiding B Hbo ICT relevant; we zien daar sinds 2015 in de instroom
    een enigszins gelijksoortige trendlijn, maar wel 1 jaar eerder. Voor
    de opleiding B Applied Data Science & Artificial Intelligence is nog
    te weinig data beschikbaar. Zie hoofdstuk [Facultaire
    ontwikkelingen].

5.  **Vrouw-man verdeling** - Het aandeel vrouwen is sinds 2013
    toegenomen van circa 31% tot circa 49%. Mogelijk dat het vernieuwde
    curriculum dat in 2012 is ingevoerd met een sterkere focus op design
    aantrekkelijker was voor vrouwen. Vrouwen zijn vaker 17-19 jaar oud
    vergeleken met mannen. Dit wijst erop dat zij al jong kiezen voor
    deze opleiding, terwijl mannen gemiddeld op wat latere leeftijd
    kiezen voor dit beroep. Zie hoofdstuk [Ontwikkeling naar geslacht].

6.  **Vooropleiding** - Met name het aandeel instroom vanuit havo en mbo
    is sterk gedaald. Leerlingen uit het mbo zijn gemiddeld 2 jaar ouder
    dan leerlingen van de havo. De belangrijkste toeleverende school is
    het ROC Mondriaan (mbo en havo), maar de aantallen per jaar zijn
    inmiddels zo laag dat statistische verbanden niet zijn aan te tonen.
    Instroom vanuit overige vooropleiding is verwaarloosbaar. Tegen de
    verwachting in is het Grafisch Lyceum Rotterdam geen grote
    toeleverancier. Zie hoofdstuk [Ontwikkeling naar vooropleiding].

7.  **Conversie** - *Nader in te vullen.* Zie hoofdstuk
    [Oriëntatiepatronen].

8.  **Directe instroom versus switch** - Sinds 2014 is het aandeel
    studenten dat direct na hun vooropleiding aan de studie is begonnen
    gedaald: van boven de 50% naar 40-45%. Naar verhouding stromen meer
    studenten in na een tussenjaar of switch. Waarom dit zo is is
    onderwerp voor gesprek. Zie hoofdstuk [Ontwikkeling naar directe of
    indirecte instroom].

9.  **Oriëntatie en aanmelding** - Sinds 2014 is de aanmelddeadline
    aangepast naar 1 mei, wat goed is terug te zien in de cijfers.
    Mannen melden zich naar verhouding later aan dan vrouwen, met
    uitzondering van 2017. In de twee coronajaren zien we naar
    verhouding nog veel late aanmeldingen bij mannen, met name in 2021.
    Dit heeft waarschijnlijk te maken met het late tijdstip waarop de
    mbo-diploma's bekend werden.

    Studenten die switchen melden zich later aan; 50% doet dit na 1 mei.
    In het coronajaar 2020 waren het vooral studenten met een switch of
    tussenjaar die zich nog laat aanmeldden. Zie hoofdstuk [Oriëntatie-
    en aanmeldpatronen].

10. **Correlaties** (tussen reistijd, vooropleiding, geslacht en datum
    van aanmelding) - Zie hoofdstuk [Correlaties].

    1.  Oudere leerlingen lijken iets vaker uit de nabije regio te
        komen.
    2.  Jongere leerlingen van de havo komen de opleiding binnen met een
        gemiddeld hoger eindexamencijfer.
    3.  Er lijkt geen verband tussen middelbare schoolcijfer, reistijd
        en hoogste vooropleiding.
    4.  Studenten met hogere eindexamencijfers melden zich vaker vroeg
        aan.
    5.  Vrouwen halen naar verhouding hogere eindexamencijfers. Het
        aanmeldgedrag van vrouwen is vergelijkbaar met mannen.

11. **Kwaliteit in Beeld** - De KiB rapportage van OKC bevestigen het
    beeld over de het marktaandeel. Veel van de studentgebonden scores
    lijken te dalen**.** Zie hoofdstuk [Onderzoek van OKC - Kwaliteit in
    Beeld].

[^2]: NB. In de data van de VH kan geen onderscheid gemaakt worden
    tussen een 3-jarige of 4-jarige variant.

\newpage

# Ontwikkeling instroom

## Algemeen beeld instroom

![Ontwikkeling instroom in aantallen
(CMD)](02_Plots/plots/{fac_opleiding_lowercase}_p001_aantallen_per_jaar.png){#fig-plot-001}

\newpage

![Ontwikkeling instroom in percentages per jaar vergeleken met het
eerste jaar
(CMD)](02_Plots/plots/{fac_opleiding_lowercase}_p002_percentage_verschil_eerste_jaar.png){#fig-plot-002}

\newpage

![Ontwikkeling instroom in percentages per jaar vergeleken met het
voorgaand jaar
(CMD)](02_Plots/plots/{fac_opleiding_lowercase}_p003_percentage_verschil_vorig_jaar.png){#fig-plot-003}

\newpage

## Regionale spreiding

![Reistijden met het OV, fiets en wandelend naar JWP \| op 16 oktober
2023, aankomst 9:00
uur](02_Plots/GIS/Reistijden-JWP.png){#fig-plot-reistijden-JWP}

\newpage

<!-- ![Reistijden met het OV, fiets en wandelend naar overige instellingen \| -->

<!-- op 16 oktober 2023, aankomst 9:00 -->

<!-- uur](02_Plots/GIS/Atlas%20Reistijden-cmd-overige.png){#fig-plot-reistijden-overige} -->

\newpage

![Spreidingsgebied CMD \|
2012](02_Plots/GIS/Instroom-B-CMD-2012.png){#fig-plot-spreiding-cmd-2012}

\newpage

![Spreidingsgebied CMD \|
2022](02_Plots/GIS/Instroom-B-CMD-2022.png){#fig-plot-spreiding-cmd-2022}

\newpage

## Landelijke ontwikkelingen

<!-- **Tabel 1a**: Instroomcijfers VH CMD - 2017-2022 -->

```{=latex}

\input{03_Includes/Instroom_VH_CMD_lineplot}
```
**NB:** De instroomcijfers van de VH zijn gebaseerd op
eerstejaarsstudenten in het hbo en verschillen daarom van de
instroomcijfers van De HHs. Daarnaast is er geen onderscheid gemaakt
tussen de 3-jarige of 4-jarige variant van CMD.

\newpage

<!-- **Tabel 2a**: Instroomcijfers VH Domein Betatechniek - 2017-2022 -->

```{=latex}

\input{03_Includes/Instroom_VH_betatechniek_lineplot}
```
\newpage

**Marktaandelen Studielink**

![Studielink martkaandelen, voltijd, nieuwe aanmeldingen,
ongewogen](02_Plots/OKC/marktaandelen_CMD_cropped.png){fig-align="center"}

\newpage

## Facultaire ontwikkelingen

![Ontwikkeling instroom alle opleidingen
ITD](02_Plots/plots/{fac_opleiding_lowercase}_p007_instroom_opleidingen_faculteit_per_jaar.png){#fig-plot-007}

\newpage

## Ontwikkeling naar geslacht

![Ontwikkeling instroom in aantallen per geslacht
(CMD)](02_Plots/plots/{fac_opleiding_lowercase}_p004_aantallen_geslacht_per_jaar.png){#fig-plot-004-cmd}

\newpage

![Ontwikkeling instroom in percentages per geslacht
(CMD)](02_Plots/plots/{fac_opleiding_lowercase}_p005_1_percentage_geslacht_per_jaar.png){#fig-plot-005-1-cmd}

\newpage

## Ontwikkeling naar vooropleiding

![Ontwikkeling instroom naar vooropleiding
(CMD)](02_Plots/plots/{fac_opleiding_lowercase}_p006_vooropleiding_2012_2021.png){#fig-plot-006-cmd}

\newpage

<!-- ![Ontwikkeling rangorde van top-5 havo-scholen -->

<!-- (CMD)](02_Plots/plots/{fac_opleiding_lowercase}_p009_2_bumpchart_havo.png){#fig-plot-009-2} -->

\newpage

## Ontwikkeling naar directe of indirecte instroom

![Ontwikkeling directe en indirecte instroom in aantallen
(CMD)](02_Plots/plots/{fac_opleiding_lowercase}_p011_1_aansluiting_aantal_per_jaar.png){#fig-plot-011-1-cmd}

\newpage

![Ontwikkeling directe en indirecte instroom in percentages
(CMD)](02_Plots/plots/{fac_opleiding_lowercase}_p011_2_aansluiting_percentage_per_jaar.png){#fig-plot-011-2-cmd}

\newpage

## Oriëntatie- en aanmeldpatronen

### Oriëntatiepatronen

<!-- ![CRM Oriëntatiedata CRM (CMD) (Bron: M&C -->

<!-- OKC)](02_Plots/OKC/Orientatie_CRM_CMD_2023.png){#fig-plot-orientatie-cmd-2023} -->

\newpage

### Aanmeldpatronen naar geslacht

![Aanmeldpatroon naar
geslacht](02_Plots/plots/{fac_opleiding_lowercase}_p012_1_2_aanmelding_geslacht_per_jaar.png){#fig-plot-012-1-2}

\newpage

### Aanmeldpatronen naar toelaatgevende vooropleiding

![Aanmeldpatroon naar
vooropleiding](02_Plots/plots/{fac_opleiding_lowercase}_p012_2_2_mbo_havo_aanmelding_vooropleiding_per_jaar.png){#fig-plot-012-2-2}

\newpage

### Aanmeldpatronen naar directe of indirecte instroom

![Aanmeldpatroon naar directe of indirecte
instroom](02_Plots/plots/{fac_opleiding_lowercase}_p012_3_2_aanmelding_aansluiting_per_jaar.png){#fig-plot-012-3-2}

\newpage

## Correlaties

![Correlatie leeftijd, vooropleiding en reistijd
(CMD)](02_Plots/plots/{fac_opleiding_lowercase}_p010_1_mbo_havo_leeftijd_reistijd_havo_mbo.png){#fig-plot-010-1}

\newpage

![Correlatie leeftijd, vooropleiding en gemiddeld eindexamencijfer
(CMD)](02_Plots/plots/{fac_opleiding_lowercase}_p010_2_havo_leeftijd_eindcijfer_havo.png){#fig-plot-010-2}

\newpage

![Correlatie vooropleiding, reistijd en gemiddeld eindexamencijfer
(CMD)](02_Plots/plots/{fac_opleiding_lowercase}_p010_3_havo_eindcijfer_reistijd_havo.png){#fig-plot-010-3}

\newpage

![Correlatie vooropleiding, datum aanmelding en gemiddeld
eindexamencijfer
(CMD)](02_Plots/plots/{fac_opleiding_lowercase}_p010_4_1_havo_aanmelddatum_eindcijfer_havo.png){#fig-plot-010-4-1}

\newpage

![Correlatie geslacht, datum aanmelding en gemiddeld eindexamencijfer
(CMD)](02_Plots/plots/{fac_opleiding_lowercase}_p010_4_2_aanmelddatum_eindcijfer_geslacht.png){#fig-plot-010-4-2}

\newpage

## Onderzoek van OKC - Kwaliteit in Beeld

![Kwaliteit in Beeld 2023 (CMD) (bron:
OKC)](02_Plots/OKC/OKC-KiB_2023_CMD.png){#fig-plot-kib-2022}

\newpage

# Mogelijk vervolgonderzoek

-   *Deficiëntie*. Wat zijn verschillen in instroom en succes tussen
    studenten die wel of geen deficiënties hebben?
-   *Switch*. Vanuit welke opleidingen switchen studenten naar de CMD?
-   *Uitval*. Welke patronen zien we in de uitval en kunnen we die
    relateren aan patronen in de instroom.
-   *Zij-instromers*. Instroompatronen van het zij-instroomprogramma.

# Versiegeschiedenis {.unnumbered}

-   dd-mm-yyyy: versie 1.0 - eerste versie voor faculteit en opleiding

\newpage

# Literatuur {.unnumbered}

::: {.content-visible when-format="pdf"}
\printbibliography[heading=none]:::

\newpage

# Bijlage 1 - Activiteiten {.unnumbered}

Voor dit onderzoek zijn de volgende activiteiten uitgevoerd:

-   **Overleg met leidinggevenden en stakeholders**:
    -   eerste gesprek met de opleidingsdirecteur op \[dd mm yyyy\]
-   **Redactie**: Theo Bakker
